// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjeajJGzPbRLK9t3eMTCXiO5xaYQj0yDY',
    appId: '1:260343473804:web:5e69be5708b8142ff6bda9',
    messagingSenderId: '260343473804',
    projectId: 'shahd-e432b',
    authDomain: 'shahd-e432b.firebaseapp.com',
    storageBucket: 'shahd-e432b.firebasestorage.app',
    measurementId: 'G-6BR0VJGG0P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaaKTVgopLLmZcdLyg-gW3lffQdPl06mw',
    appId: '1:260343473804:android:f42ed1cbc0048257f6bda9',
    messagingSenderId: '260343473804',
    projectId: 'shahd-e432b',
    storageBucket: 'shahd-e432b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT9EagTcUbhAkqLYGijCVqhtWzlMRwzTU',
    appId: '1:260343473804:ios:b5896bfc702c94fbf6bda9',
    messagingSenderId: '260343473804',
    projectId: 'shahd-e432b',
    storageBucket: 'shahd-e432b.firebasestorage.app',
    iosBundleId: 'com.example.firstproj',
  );
}
